// correct: 0 = A, 1 = B, 2 = C, 3 = D.
// revealImage se muestra únicamente después de revelar la respuesta.
const categories = [
 {id:'football',name:'Fútbol',label:'FÚTBOL',color:'#04e447',icon:'⚽'},
 {id:'basket',name:'Básquet',label:'BÁSQUET',color:'#f181b0',icon:'◉'},
 {id:'tennis',name:'Tenis',label:'TENIS',color:'#fff5e7',icon:'◎'},
 {id:'f1',name:'Fórmula 1',label:'FÓRMULA 1',color:'#b4ed9b',icon:'⚑'},
 {id:'olympics',name:'Juegos Olímpicos',label:'JJ. OO.',color:'#fac1e6',icon:'✳'}
];
const questions = [
 {category:'football',question:'¿Qué club empezó a usar el logo de Jordan en su camiseta en 2018?',options:['Real Madrid','Paris Saint-Germain','Manchester United','Juventus'],correct:1,revealImage:'assets/reveal-psg.jpg',caption:'Michael Jordan con una camiseta del PSG · AS, 2018',explanation:'El PSG. La colaboración con Jordan incluyó las camisetas de Champions y una colección de ropa para usar fuera de la cancha.',debate:'¿Te pondrías una camiseta de tu clásico rival porque te gusta el diseño?',source:'https://en.news.psg.fr/press-releases/club/paris-saint-germain-and-jordan-brand-team-up-a-first-for-football'},
 {category:'football',question:'¿Qué modelo de adidas nació para jugar al fútbol sobre superficies heladas?',options:['Gazelle','Stan Smith','Samba','Superstar'],correct:2,revealImage:'assets/reveal-samba.jpg',caption:'adidas Samba OG · Wikimedia Commons',explanation:'Las Samba. Su historia arranca en el fútbol de los años 50, con una suela pensada para tener agarre sobre canchas heladas. Las de la foto son una versión actual.',debate:'¿Las Samba te siguen gustando o ya te cansaste de verlas?',source:'https://www.adidas.com/us/blog/1060276-we-gave-the-world-a-samba-a-legendary-shoe-with-a-rich-history'},
 {category:'basket',question:'¿En qué año salieron las primeras Air Jordan 1?',options:['1975','1985','1995','2005'],correct:1,revealImage:'assets/reveal-jordan.jpg',caption:'Nike Air Jordan I · Wikimedia Commons',explanation:'En 1985. Las diseñó Peter Moore y fueron el primer modelo de la línea de Michael Jordan.',debate:'¿Cuánto de lo que pagás por unas Jordan es la zapatilla y cuánto es el nombre?',source:'https://www.nike.com/gb/a/air-jordan-1-history'},
 {category:'basket',question:'Cuando hablan de “tunnel fits” en la NBA, ¿de qué están hablando?',options:['La ropa de entrenamiento','Una colección de zapatillas','El look para llegar al estadio','Los trajes de los entrenadores'],correct:2,revealImage:'assets/tunnel.jpg',caption:'Jordan Clarkson · NBA.com',explanation:'De la ropa que llevan al llegar al estadio, antes de jugar.',debate:'¿Quién tiene más presión: el que se viste bien siempre o el que aparece una vez con un look rarísimo?',source:'https://www.nba.com/news/jordan-clarkson-from-tunnel-to-runway'},
 {category:'basket',question:'Remeras enormes, pantalones anchos y cadenas: ¿qué estilo llevó Iverson a la NBA?',options:['Preppy','Grunge','Punk','Hip-hop'],correct:3,revealImage:'assets/reveal-iverson.jpg',caption:'Allen Iverson repasa sus looks · GQ Sports, 2023',explanation:'El del hip-hop. Iverson se vestía como la gente con la que había crecido: ropa ancha, cadenas y durags. Defendió esa forma de vestir cuando la liga empezó a exigir más formalidad.',debate:'¿Vestirse de traje te hace más profesional? ¿O a Iverson le discutían otra cosa?',source:'https://www.gq.com/story/allen-iverson-style-hall-of-fame-february-cover'},
 {category:'tennis',question:'¿Qué Grand Slam exige que la ropa sea casi toda blanca?',options:['Roland Garros','US Open','Australian Open','Wimbledon'],correct:3,revealImage:'assets/reveal-wimbledon.jpg',caption:'Garbiñe Muguruza y su conjunto para Wimbledon 2019 · WTA',explanation:'Wimbledon. La regla también alcanza a las zapatillas y limita los detalles de color.',debate:'¿El blanco es parte de la gracia de Wimbledon o ya podrían dejar que cada uno elija?',source:'https://www.wimbledon.com/en_GB/about_wimbledon/clothing_and_equipment.html'},
 {category:'tennis',question:'¿De dónde salió el cocodrilo del logo de Lacoste?',options:['Del apodo de René Lacoste','De la mascota de un torneo','Del escudo de su ciudad','De un dibujo de su primer socio'],correct:0,revealImage:'assets/reveal-lacoste.jpg',caption:'René Lacoste con el cocodrilo en el pecho · Wikimedia Commons',explanation:'A René Lacoste le decían “El Cocodrilo” cuando jugaba al tenis. Después llevó ese apodo a la marca.',debate:'Dos chombas iguales, una con cocodrilo y otra sin logo: ¿cuánto más pagarías por la primera?',source:'https://www.rolandgarros.com/en-us/article/rene-lacoste-icone-lifestyle-joueur-stade'},
 {category:'f1',question:'¿Qué piloto fue uno de los anfitriones de la Met Gala 2025?',options:['Max Verstappen','Fernando Alonso','Lewis Hamilton','Carlos Sainz'],correct:2,revealImage:'assets/f1.jpg',caption:'Lewis Hamilton, Anna Wintour y Pharrell Williams · Formula1.com, 2024',explanation:'Lewis Hamilton fue uno de los copresidentes de la gala. La foto es de 2024, cuando se anunció su participación.',debate:'¿Hamilton te parece un referente de moda o simplemente alguien que se anima a usar de todo?',source:'https://www.formula1.com/en/latest/article/fashion-and-formula-1-the-new-collaboration.zU6HWhIazigSpq8NeZZzm'},
 {category:'f1',question:'¿Quién se convirtió en embajador de Dior en China en 2023?',options:['Yuki Tsunoda','Zhou Guanyu','Alex Albon','Oscar Piastri'],correct:1,revealImage:'assets/reveal-zhou.jpg',caption:'Zhou Guanyu · Sitio oficial del piloto, entrevista sobre su estilo de 2023',explanation:'Zhou Guanyu. En 2023 contó que había empezado a trabajar con Dior como embajador.',debate:'¿Alguna vez te dieron ganas de comprar algo porque se lo viste a un deportista?',source:'https://www.zhou-guanyu.com/en/news/detail/152'},
 {category:'olympics',question:'¿Qué delegación llevó los uniformes de Michel & Amazonka en París 2024?',options:['Japón','Mongolia','Corea del Sur','Kazajistán'],correct:1,revealImage:'assets/mongolia.jpg',caption:'Uniformes de Mongolia para París 2024 · Michel & Amazonka / GQ',explanation:'Mongolia. Los diseños recuperaban prendas y bordados de la vestimenta tradicional del país.',debate:'¿Argentina tendría que ir con algo más propio? ¿Qué le pondrías a la delegación?',source:'https://www.gq.com/story/mongolia-olympics-2024-uniforms-interview'},
 {category:'olympics',question:'¿Qué marca vistió a Estados Unidos en los desfiles de París 2024?',options:['Tommy Hilfiger','Calvin Klein','Ralph Lauren','Coach'],correct:2,revealImage:'assets/reveal-usa.jpg',caption:'Ropa de apertura y clausura de Estados Unidos, París 2024 · Ralph Lauren',explanation:'Ralph Lauren. Preparó la ropa para los desfiles de apertura y clausura de los Juegos Olímpicos y Paralímpicos.',debate:'¿Para un desfile así elegís traje, jeans o equipo deportivo?',source:'https://corporate.ralphlauren.com/pr_240618_PoloRalphLaurenTeamUSA2024.html'}
];
