// correct: 0 = A, 1 = B, 2 = C, 3 = D.
// revealImage se muestra únicamente después de revelar la respuesta.
const categories = [
 {id:'football',name:'Fútbol',label:'FÚTBOL',color:'#04e447',icon:'⚽'},
 {id:'basket',name:'Básquet',label:'BÁSQUET',color:'#f181b0',icon:'◉'},
 {id:'tennis',name:'Tenis',label:'TENIS',color:'#fff5e7',icon:'◎'},
 {id:'f1',name:'Fórmula 1',label:'FÓRMULA 1',color:'#b4ed9b',icon:'⚑'},
 {id:'olympics',name:'Juegos Olímpicos',label:'JJ. OO.',color:'#fac1e6',icon:'✳'}
];

const questions = [
 {category:'football',question:'¿Qué dos cracks protagonizaron juntos una campaña de Louis Vuitton jugando al ajedrez?',options:['Messi y Cristiano Ronaldo','Messi y Neymar','Cristiano Ronaldo y Mbappé','Messi y Beckham'],correct:0,revealImage:'assets/news/messi.jpg',caption:'Lionel Messi',explanation:'Lionel Messi y Cristiano Ronaldo. La campaña salió antes del Mundial de Qatar y fue una de esas fotos que parecían imposibles de juntar.',debate:'¿Una campaña así vende ropa o vende el momento histórico?',source:'https://www.louisvuitton.com/'},
 {category:'football',question:'Además de jugar al fútbol, ¿qué producto lanzó Cristiano Ronaldo bajo la marca CR7?',options:['Perfumes y ropa interior','Vestidos de alta costura','Botines de rugby','Relojes para árbitros'],correct:0,revealImage:'assets/news/cr7.jpg',caption:'Cristiano Ronaldo',explanation:'Perfumes y ropa interior. CR7 convirtió su nombre y su imagen en una marca que va bastante más allá del fútbol.',debate:'¿Comprás una prenda porque te gusta o porque lleva el nombre de alguien?',source:'https://www.cr7fragrances.store/'},
 {category:'football',question:'¿Qué jugador de la Selección suele aparecer con looks jugados, uñas pintadas y prendas oversize?',options:['Ángel Di María','Rodrigo De Paul','Lautaro Martínez','Nicolás Otamendi'],correct:1,revealImage:'assets/news/rodrigo.jpg',caption:'Rodrigo De Paul',explanation:'Rodrigo De Paul. Dentro de la Selección es uno de los que más usa la ropa para mostrar personalidad.',debate:'¿En el fútbol todavía se juzga más la ropa de un jugador que en otros ambientes?',source:'https://www.instagram.com/rodridepaul/'},
 {category:'basket',question:'¿Qué jugador creó Curry Brand junto a Under Armour?',options:['LeBron James','Stephen Curry','Kevin Durant','Kyrie Irving'],correct:1,revealImage:'assets/news/curry.jpg',caption:'Stephen Curry',explanation:'Stephen Curry. Su línea creció hasta convertirse en una marca propia dentro de Under Armour.',debate:'¿Una marca con nombre de jugador puede competir de verdad con Jordan?',source:'https://about.underarmour.com/en/stories/2020/11/introducing-curry-brand.html'},
 {category:'basket',question:'Cuando hablan de “tunnel fits” en la NBA, ¿de qué están hablando?',options:['La ropa de entrenamiento','Una colección de zapatillas','El look para llegar al estadio','Los trajes de los entrenadores'],correct:2,revealImage:'assets/news/clarkson.jpg',caption:'Jordan Clarkson',explanation:'Del look con el que los jugadores llegan al estadio. Jordan Clarkson es uno de los nombres que convirtió ese pasillo en una pasarela.',debate:'¿El look de llegada ya es parte del espectáculo o distrae del partido?',source:'https://www.nba.com/news/jordan-clarkson-from-tunnel-to-runway'},
 {category:'basket',question:'Remeras enormes, pantalones anchos y cadenas: ¿qué estilo llevó Iverson a la NBA?',options:['Preppy','Grunge','Punk','Hip-hop'],correct:3,revealImage:'assets/news/iverson.jpg',caption:'Allen Iverson',explanation:'El hip-hop. Iverson llevó a la NBA la estética con la que se identificaba fuera de la cancha y terminó cambiando la imagen de toda una generación.',debate:'¿El código de vestimenta de la NBA buscaba prolijidad o controlar una cultura?',source:'https://www.gq.com/story/allen-iverson-style-hall-of-fame-february-cover'},
 {category:'tennis',question:'¿Qué tenista se convirtió en socio de la marca suiza On después de dejar Nike?',options:['Rafael Nadal','Roger Federer','Novak Djokovic','Andy Murray'],correct:1,revealImage:'assets/news/federer.jpg',caption:'Roger Federer',explanation:'Roger Federer. No fue sólo la cara de la marca: también invirtió y trabajó en el desarrollo de su línea de zapatillas.',debate:'¿Te interesa más una colaboración cuando el deportista participa del diseño?',source:'https://www.on.com/en-us/explore/roger-federer'},
 {category:'tennis',question:'¿Qué prenda hizo inconfundible el look de Nadal en sus primeros años?',options:['La camisa con cuello','La musculosa','El saco blanco','El chaleco tejido'],correct:1,revealImage:'assets/news/nadal.jpg',caption:'Rafael Nadal',explanation:'La musculosa. Con los pantalones largos tipo pirata armó una silueta que todavía se asocia con sus primeros años en el circuito.',debate:'¿Qué look deportivo de otra época debería volver?',source:'https://www.nike.com/'},
 {category:'tennis',question:'¿Qué campeona fue nombrada embajadora de Louis Vuitton en 2021?',options:['Naomi Osaka','Iga Świątek','Coco Gauff','Aryna Sabalenka'],correct:0,revealImage:'assets/news/naomi.jpg',caption:'Naomi Osaka',explanation:'Naomi Osaka. Su relación con la moda incluye campañas, tapas y colaboraciones mucho más allá de la ropa de tenis.',debate:'¿La moda ayuda a conocer la personalidad de un deportista o fabrica un personaje?',source:'https://us.louisvuitton.com/eng-us/magazine/articles/naomi-osaka-joins-louis-vuitton-as-new-house-ambassador'},
 {category:'tennis',question:'¿Qué tenista usó un catsuit negro en Roland Garros 2018 y abrió un debate sobre la vestimenta?',options:['Venus Williams','Serena Williams','Naomi Osaka','Sloane Stephens'],correct:1,revealImage:'assets/news/serena.jpg',caption:'Serena Williams',explanation:'Serena Williams. El catsuit tenía una función médica, pero también terminó siendo una de las imágenes de moda más recordadas del tenis.',debate:'¿Hasta dónde debería poder opinar un torneo sobre la ropa de sus atletas?',source:'https://www.nike.com/'},
 {category:'tennis',question:'¿Qué argentina convirtió su apellido en una conocida línea de perfumes?',options:['Paola Suárez','Gabriela Sabatini','Gisela Dulko','Nadia Podoroska'],correct:1,revealImage:'assets/news/sabatini.jpg',caption:'Gabriela Sabatini',explanation:'Gabriela Sabatini. Fue una de las primeras deportistas argentinas en transformar su imagen en una marca internacional de belleza.',debate:'¿Qué deportista argentino de hoy podría tener una marca propia fuera del deporte?',source:'https://www.gabriela-sabatini.com/'},
 {category:'f1',question:'¿Qué piloto argentino hizo volver el mate al paddock de la Fórmula 1?',options:['José María López','Franco Colapinto','Agustín Canapino','Esteban Guerrieri'],correct:1,revealImage:'assets/news/colapinto.jpg',caption:'Franco Colapinto',explanation:'Franco Colapinto. Entre el mate y sus looks relajados, llevó una imagen muy argentina a un ambiente bastante calculado.',debate:'¿La naturalidad de Colapinto es parte de su atractivo para las marcas?',source:'https://www.formula1.com/'},
 {category:'f1',question:'¿Qué piloto de Ferrari es embajador de Puma y suele mezclar sastrería con looks deportivos?',options:['Charles Leclerc','Lando Norris','George Russell','Pierre Gasly'],correct:0,revealImage:'assets/news/leclerc.jpg',caption:'Charles Leclerc',explanation:'Charles Leclerc. Su imagen combina la estética clásica de Ferrari con campañas y prendas mucho más urbanas.',debate:'¿Ferrari vende más autos, deporte o estilo de vida?',source:'https://about.puma.com/'},
 {category:'f1',question:'¿Qué piloto japonés lanzó su propia marca de ropa llamada Venti Due?',options:['Kamui Kobayashi','Yuki Tsunoda','Takuma Sato','Kazuki Nakajima'],correct:1,revealImage:'assets/news/yuki.jpg',caption:'Yuki Tsunoda',explanation:'Yuki Tsunoda. Venti Due significa “veintidós” en italiano, el número con el que corrió durante buena parte de su carrera en F1.',debate:'¿Una marca de piloto tiene que parecerse al automovilismo o conviene que vaya por otro lado?',source:'https://www.instagram.com/ventidue22/'},
 {category:'f1',question:'¿Qué campeón argentino de Fórmula 1 era famoso por aparecer siempre impecable de traje?',options:['Carlos Reutemann','Juan Manuel Fangio','Oscar Gálvez','José Froilán González'],correct:1,revealImage:'assets/news/fangio.jpg',caption:'Juan Manuel Fangio',explanation:'Juan Manuel Fangio. Su imagen pública quedó ligada a una elegancia clásica, muy distinta al estilo informal de los pilotos actuales.',debate:'¿Los pilotos de antes tenían más elegancia o simplemente menos libertad para vestirse?',source:'https://www.museofangio.com/'},
 {category:'olympics',question:'¿Qué campeona olímpica argentina es médica además de judoca?',options:['Paula Pareto','Delfina Pignatiello','Cecilia Carranza','Georgina Bardach'],correct:0,revealImage:'assets/news/pareto.jpg',caption:'Paula Pareto',explanation:'Paula Pareto. Ganó el oro en Río 2016 y construyó una imagen pública donde el guardapolvo y el judogi pesan más que cualquier producción de moda.',debate:'¿La ropa de trabajo también puede convertirse en parte de una marca personal?',source:'https://olympics.com/'},
 {category:'olympics',question:'¿Qué referente de Las Leonas fue elegida ocho veces como la mejor jugadora del mundo?',options:['Soledad García','Luciana Aymar','Cecilia Rognoni','Magdalena Aicega'],correct:1,revealImage:'assets/news/lucha aimar.jpg',caption:'Luciana Aymar',explanation:'Luciana Aymar. Su figura trascendió el hockey y se volvió una de las imágenes más reconocibles del deporte argentino.',debate:'¿Por qué a las deportistas se les pregunta mucho más seguido por su ropa que a los varones?',source:'https://olympics.com/'}
];

